CREATE TABLE STOCK_MASTER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SECURITY_CODE VARCHAR(100),
    ISSUER_NAME VARCHAR(100),
    SECURITY_ID VARCHAR(100),
    SECURITY_NAME VARCHAR(200),
    STATUS VARCHAR(100),
    GROUPC VARCHAR(20)
    FACE_VALUE FLOAT,
    ISIN_NO VARCHAR(100),
    INDUSTRY VARCHAR(200)
)